# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# Pods for RestaurantsByPostcode
def common_pods
    pod 'SwiftLint'
    pod 'Moya'
    pod 'PromiseKit'
    pod 'Kingfisher'
end

# Pods for Testing
def test_pods
    pod "Quick"
    pod "Nimble"
    pod "Nimble-Snapshots"
end

target 'RestaurantsByPostcode' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  common_pods

  # Pods for RestaurantsByPostcode

  target 'RestaurantsByPostcodeTests' do
    inherit! :search_paths
    # Pods for testing
    test_pods
  end

end

target 'RestaurantsByPostcodeUITests' do
  # Pods for testing
  end
